/*
 * SelectPlayersPanel.java
 *
 * Created on 17 Νοέμβριος 2007, 1:50 πμ
 */

package agentgame.gui;

import java.util.Vector;

import agentgame.logic.FiniteStateMachine;
import agentgame.logic.IPlayer;
import agents.*;

/**
 *
 * @author  anjelinio
 */
public class SelectPlayersPanel extends javax.swing.JPanel {    
    
    /** 
     *  Defines the interface for event listeners, for when I've made my mind
     *  up on the two players ... 
     */
    public interface ISelectionListener {
        public void selectionMade(IPlayer player1, IPlayer player2);
    }
    
    private Vector eventListeners = new Vector();
    
    public void addSelectionListener(ISelectionListener listener){
        eventListeners.add(listener);
    }
    
    public void removeSelectionListener(ISelectionListener listener){
        eventListeners.remove(listener);
    }
    
    private void notifyListeners(IPlayer player1, IPlayer player2){
        java.util.Iterator<Object> listeners = eventListeners.iterator();        
        while(listeners.hasNext()){
            ((ISelectionListener)listeners.next()).selectionMade(player1, player2);
        }
    }
    
    private TicTacToeForm parentFrame = null;
    
    /** Creates new form SelectPlayersPanel */
    public SelectPlayersPanel(TicTacToeForm parentFrame) {
        initComponents();
        
        this.parentFrame = parentFrame;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        cmbPlayer1Type = new javax.swing.JComboBox();
        cmbPlayer2Type = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Player 1:");

        cmbPlayer1Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "Silly Computer", "Complicated Silly Computer" }));

        cmbPlayer2Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "Silly Computer", "Complicated Silly Computer" }));

        jLabel2.setText("Player 2:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPlayer2Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbPlayer1Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPlayer1Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbPlayer2Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // okay. What i need to do is ... read the two selected values, and
        // create player instances accordingly. Then, notify listeners and
        // off we go
        
        // TODO: read in the values and create the instances ... 
        
        String[] selectedValues = new String[] {"", ""};
        
        selectedValues[0] = (String)cmbPlayer1Type.getSelectedItem();
        selectedValues[1] = (String)cmbPlayer2Type.getSelectedItem();
        
        IPlayer[] players = new IPlayer[] {null, null};
        for(int i=0; i<selectedValues.length; i++){
            
            FiniteStateMachine.State playerState = (0<i)?FiniteStateMachine.State.nought : FiniteStateMachine.State.cross;
            
            if("Human".equals(selectedValues[i])){
                players[i] = new GuiPlayer(parentFrame, playerState);
            }
            else if("Silly Computer".equals(selectedValues[i])){
                players[i] = new ComputerPlayer(playerState);
            }
            else if("Complicated Silly Computer".equals(selectedValues[i])){
                players[i] = new SmarterComputerPlayer(playerState);
            }
        }
        
        notifyListeners(players[0], players[1]);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbPlayer1Type;
    private javax.swing.JComboBox cmbPlayer2Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}


