/*
 * TicTacToeForm.java
 *
 * Created on 16 Νοέμβριος 2007, 10:48 μμ
 */

package agentgame.gui;

import agentgame.logic.IPlayer;
import agentgame.logic.Facade;
import agentgame.logic.FiniteStateMachine;

import javax.swing.*;

import java.lang.Runnable;
import java.lang.Thread;

/**
 *
 * @author  anjelinio
 */
public class TicTacToeForm extends javax.swing.JFrame implements SelectPlayersPanel.ISelectionListener, Facade.IStateChangedListener {
    
    /** Creates new form TicTacToeForm */
    public TicTacToeForm() {
        initComponents();
        
        this.labels = new JLabel[][] { 
            new JLabel[] {txt00, txt01, txt02},
            new JLabel[] {txt10, txt11, txt12},
            new JLabel[] {txt20, txt21, txt22}
        };
    }
    
    // <editor-fold desc="private members">
    
    private IPlayer player1 = null;
    private IPlayer player2 = null;
    
    private Facade facade = null;
    
    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc=" select players panel code ">
    
    private SelectPlayersPanel selectPlayers = null;
    
    protected SelectPlayersPanel getSelectPlayersPanel(){
        if(null==selectPlayers){
            selectPlayers = new SelectPlayersPanel(this);
            selectPlayers.addSelectionListener(this);
        }
        
        return selectPlayers;
    }
    
    // </editor-fold>
    
    private JFrame selectPlayersFrame = null;
    
    /**
     *  resets everything, and start a new game, all the way
     *  back from selecting two players ... 
     */
    protected void reset() {
        // nullify e v e r y t h i n g   ! ! !  :D
        player1 = null;
        player2 = null;    
        facade = null; 
         
        selectPlayersFrame = new JFrame("Select Players");
        selectPlayersFrame.getContentPane().add(getSelectPlayersPanel());
        selectPlayersFrame.pack();       
        
        selectPlayersFrame.setVisible(true);            
    }
    
    private JLabel[][] labels = null;
    
    public void stateChanged(FiniteStateMachine currentBoard){
        // okay, enumerate and set texts ... 
        for(int row = 0; row<FiniteStateMachine.NUMBEROFROWS; row++){
            for(int column = 0; column<FiniteStateMachine.NUMBEROFCOLUMNS; column++){
                FiniteStateMachine.State currState = currentBoard.getCellState(row, column);
                String strVal = ". . .";
                if(currState.equals(FiniteStateMachine.State.cross)){
                    strVal = "X";
                }
                else if (currState.equals(FiniteStateMachine.State.nought)){
                    strVal = "O";
                }                  
                        
                this.labels[row][column].setText(strVal);
            }
        }
    }    
    
    public void selectionMade(IPlayer player1, IPlayer player2){
        // ok, get the players and be done with it ... 
        this.player1 = player1;
        this.player2 = player2;
        
        if(facade!=null){
            facade.dispose();
        }
        
        facade = new Facade(player1, player2);
        facade.addSelectionListener(this);
        
        java.lang.Thread newThread = new java.lang.Thread(new Runnable() {
            public void run() {
                // okay, new game, two players, here we go ... @!                
                facade.begin();
            }
        }); 
        
        newThread.start();
        
        selectPlayersFrame.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        controlPanel = new javax.swing.JPanel();
        scorePanel = new javax.swing.JPanel();
        lblPlayer1 = new javax.swing.JLabel();
        lblScore1 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        lblScore2 = new javax.swing.JLabel();
        emptyPanel = new javax.swing.JPanel();
        newGameButtonPanel = new javax.swing.JPanel();
        newGameButton = new javax.swing.JButton();
        gamePanel = new javax.swing.JPanel();
        grid00 = new javax.swing.JPanel();
        txt00 = new javax.swing.JLabel();
        grid01 = new javax.swing.JPanel();
        txt01 = new javax.swing.JLabel();
        grid02 = new javax.swing.JPanel();
        txt02 = new javax.swing.JLabel();
        grid10 = new javax.swing.JPanel();
        txt10 = new javax.swing.JLabel();
        grid11 = new javax.swing.JPanel();
        txt11 = new javax.swing.JLabel();
        grid12 = new javax.swing.JPanel();
        txt12 = new javax.swing.JLabel();
        grid20 = new javax.swing.JPanel();
        txt20 = new javax.swing.JLabel();
        grid21 = new javax.swing.JPanel();
        txt21 = new javax.swing.JLabel();
        grid22 = new javax.swing.JPanel();
        txt22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agent Tic Tac Toe");
        controlPanel.setLayout(new java.awt.BorderLayout());

        controlPanel.setMaximumSize(new java.awt.Dimension(68, 54));
        controlPanel.setMinimumSize(new java.awt.Dimension(68, 54));
        scorePanel.setLayout(new java.awt.GridLayout(2, 2));

        scorePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Scores:"));
        scorePanel.setMaximumSize(new java.awt.Dimension(68, 54));
        scorePanel.setMinimumSize(new java.awt.Dimension(68, 54));
        scorePanel.setPreferredSize(new java.awt.Dimension(68, 54));
        scorePanel.setRequestFocusEnabled(false);
        lblPlayer1.setText("Player 1:");
        scorePanel.add(lblPlayer1);

        scorePanel.add(lblScore1);

        lblPlayer2.setText("Player 2:");
        scorePanel.add(lblPlayer2);

        scorePanel.add(lblScore2);

        controlPanel.add(scorePanel, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout emptyPanelLayout = new javax.swing.GroupLayout(emptyPanel);
        emptyPanel.setLayout(emptyPanelLayout);
        emptyPanelLayout.setHorizontalGroup(
            emptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );
        emptyPanelLayout.setVerticalGroup(
            emptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        controlPanel.add(emptyPanel, java.awt.BorderLayout.CENTER);

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newGameButtonPanelLayout = new javax.swing.GroupLayout(newGameButtonPanel);
        newGameButtonPanel.setLayout(newGameButtonPanelLayout);
        newGameButtonPanelLayout.setHorizontalGroup(
            newGameButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newGameButtonPanelLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(newGameButton)
                .addContainerGap())
        );
        newGameButtonPanelLayout.setVerticalGroup(
            newGameButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newGameButtonPanelLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(newGameButton)
                .addContainerGap())
        );
        controlPanel.add(newGameButtonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(controlPanel, java.awt.BorderLayout.EAST);

        gamePanel.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        gamePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        gamePanel.setMinimumSize(new java.awt.Dimension(334, 304));
        grid00.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt00.setFont(new java.awt.Font("Tahoma", 0, 36));
        txt00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt00.setText("O");
        txt00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt00MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grid00Layout = new javax.swing.GroupLayout(grid00);
        grid00.setLayout(grid00Layout);
        grid00Layout.setHorizontalGroup(
            grid00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid00Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txt00)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        grid00Layout.setVerticalGroup(
            grid00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid00Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txt00)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        gamePanel.add(grid00);

        grid01.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt01.setFont(new java.awt.Font("Tahoma", 0, 36));
        txt01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt01.setText("O");
        txt01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt01MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grid01Layout = new javax.swing.GroupLayout(grid01);
        grid01.setLayout(grid01Layout);
        grid01Layout.setHorizontalGroup(
            grid01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid01Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txt01)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        grid01Layout.setVerticalGroup(
            grid01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid01Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txt01)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        gamePanel.add(grid01);

        grid02.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt02.setFont(new java.awt.Font("Tahoma", 0, 36));
        txt02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt02.setText("O");
        txt02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt02MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grid02Layout = new javax.swing.GroupLayout(grid02);
        grid02.setLayout(grid02Layout);
        grid02Layout.setHorizontalGroup(
            grid02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid02Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txt02)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        grid02Layout.setVerticalGroup(
            grid02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid02Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txt02)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        gamePanel.add(grid02);

        grid10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt10.setFont(new java.awt.Font("Tahoma", 0, 36));
        txt10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt10.setText("O");
        txt10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grid10Layout = new javax.swing.GroupLayout(grid10);
        grid10.setLayout(grid10Layout);
        grid10Layout.setHorizontalGroup(
            grid10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txt10)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        grid10Layout.setVerticalGroup(
            grid10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txt10)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        gamePanel.add(grid10);

        grid11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt11.setFont(new java.awt.Font("Tahoma", 0, 36));
        txt11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt11.setText("O");
        txt11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grid11Layout = new javax.swing.GroupLayout(grid11);
        grid11.setLayout(grid11Layout);
        grid11Layout.setHorizontalGroup(
            grid11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grid11Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(txt11)
                .addGap(23, 23, 23))
        );
        grid11Layout.setVerticalGroup(
            grid11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txt11)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        gamePanel.add(grid11);

        grid12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt12.setFont(new java.awt.Font("Tahoma", 0, 36));
        txt12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt12.setText("O");
        txt12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grid12Layout = new javax.swing.GroupLayout(grid12);
        grid12.setLayout(grid12Layout);
        grid12Layout.setHorizontalGroup(
            grid12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid12Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txt12)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        grid12Layout.setVerticalGroup(
            grid12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txt12)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        gamePanel.add(grid12);

        grid20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt20.setFont(new java.awt.Font("Tahoma", 0, 36));
        txt20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt20.setText("O");
        txt20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grid20Layout = new javax.swing.GroupLayout(grid20);
        grid20.setLayout(grid20Layout);
        grid20Layout.setHorizontalGroup(
            grid20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid20Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txt20)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        grid20Layout.setVerticalGroup(
            grid20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grid20Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(txt20)
                .addGap(36, 36, 36))
        );
        gamePanel.add(grid20);

        grid21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt21.setFont(new java.awt.Font("Tahoma", 0, 36));
        txt21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt21.setText("O");
        txt21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grid21Layout = new javax.swing.GroupLayout(grid21);
        grid21.setLayout(grid21Layout);
        grid21Layout.setHorizontalGroup(
            grid21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid21Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txt21)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        grid21Layout.setVerticalGroup(
            grid21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid21Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txt21)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        gamePanel.add(grid21);

        grid22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt22.setFont(new java.awt.Font("Tahoma", 0, 36));
        txt22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt22.setText("O");
        txt22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grid22Layout = new javax.swing.GroupLayout(grid22);
        grid22.setLayout(grid22Layout);
        grid22Layout.setHorizontalGroup(
            grid22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid22Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txt22)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        grid22Layout.setVerticalGroup(
            grid22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid22Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txt22)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        gamePanel.add(grid22);

        getContentPane().add(gamePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold desc="label clicks">
    private void txt22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt22MouseClicked
        labelClicked(2, 2);
    }//GEN-LAST:event_txt22MouseClicked

    private void txt21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt21MouseClicked
        labelClicked(2, 1);
    }//GEN-LAST:event_txt21MouseClicked

    private void txt20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt20MouseClicked
        labelClicked(2, 0);
    }//GEN-LAST:event_txt20MouseClicked

    private void txt12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt12MouseClicked
        labelClicked(1, 2);
    }//GEN-LAST:event_txt12MouseClicked

    private void txt11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt11MouseClicked
        labelClicked(1, 1);
    }//GEN-LAST:event_txt11MouseClicked

    private void txt10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt10MouseClicked
        labelClicked(1, 0);
    }//GEN-LAST:event_txt10MouseClicked

    private void txt02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt02MouseClicked
        labelClicked(0, 2);
    }//GEN-LAST:event_txt02MouseClicked

    private void txt01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt01MouseClicked
        labelClicked(0, 1);
    }//GEN-LAST:event_txt01MouseClicked

    private void txt00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt00MouseClicked
        labelClicked(0, 0);
    }//GEN-LAST:event_txt00MouseClicked
    //</editor-fold>
    
    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        reset();
    }//GEN-LAST:event_newGameButtonActionPerformed
    
    private void labelClicked(int row, int column){
        notifyListeners(row, column);
    }    
    
    private java.util.Vector eventListeners = new java.util.Vector();
    
    public void addSelectionListener(ILabelClickListener listener){
        eventListeners.add(listener);
    }
    
    public void removeSelectionListener(ILabelClickListener listener){
        eventListeners.remove(listener);
    }
    
    private void notifyListeners(int row, int column){
        java.util.Iterator<Object> listeners = eventListeners.iterator();        
        while(listeners.hasNext()){
            ((ILabelClickListener)listeners.next()).selectionMade(row, column);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel emptyPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel grid00;
    private javax.swing.JPanel grid01;
    private javax.swing.JPanel grid02;
    private javax.swing.JPanel grid10;
    private javax.swing.JPanel grid11;
    private javax.swing.JPanel grid12;
    private javax.swing.JPanel grid20;
    private javax.swing.JPanel grid21;
    private javax.swing.JPanel grid22;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblScore1;
    private javax.swing.JLabel lblScore2;
    private javax.swing.JButton newGameButton;
    private javax.swing.JPanel newGameButtonPanel;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JLabel txt00;
    private javax.swing.JLabel txt01;
    private javax.swing.JLabel txt02;
    private javax.swing.JLabel txt10;
    private javax.swing.JLabel txt11;
    private javax.swing.JLabel txt12;
    private javax.swing.JLabel txt20;
    private javax.swing.JLabel txt21;
    private javax.swing.JLabel txt22;
    // End of variables declaration//GEN-END:variables
    
}
